// Generated by CoffeeScript 1.8.0
var Player, player;

Player = require('player');

player = new Player('./schule.mp3');

$(function() {
  $('#button-play').click(function() {
    player.play(function(err, plr) {
      console.log('playing');
    });
  });
});
